### ISSUE TITLE
@ and @@ text block formatting appears to halt when encountering the ' character - v54

### ISSUE THREAD

**Issue by gesslar** [jlchmura/prettier-lpc-vscode#18] opened 2023-05-27 01:14 UTC
In one file, I have this text block
```c
	        set("long", @text

   The soft, black and white pelt has been expertly cured to preserve the 
texture and hairs of the panda's fur. Though the skin is quite beautiful,
the animal itself must have been even more majestic.

text
);
```
![image](https://github.com/jlchmura/prettier-lpc-vscode/assets/1266935/44ca2dd6-5849-4359-8921-7544d8b6aa9b)

and the formatter halted, with the cursor right between the word `fur` and the following `.`. Suspect the `'` character might have tripped it.

In another file,

I have this block
```c
    set("long", @text

   This disgusting yet fierce looking beast is similar to a normal pig, but 
it is larger, more muscled, and bears sharp, curved tusks! It stares at you 
with hate in its eyes and a definite thirst for your blood in its heart. Its 
flesh is covered in mud which certainly doesn't help its appearance or its 
foul smell!

text //'
);
```
and the formatter halted with the cursor right before the `//'` on the second last line.
![image](https://github.com/jlchmura/prettier-lpc-vscode/assets/1266935/89acabdb-6b93-427f-b726-902fbe4ba334)

Again, this is just speculation on the cause.

**Comment by jlchmura** [comment] 2023-06-21 15:54
Fixed in v57

**Comment by jlchmura** [comment] 2023-06-23 11:45
The first part of this ticket is still happening.  It is terminating the string block too early on the characters `text` in `texture`.

**Comment by jlchmura** [comment] 2023-06-23 12:34
Ok, finally got this one.  The first part of the issue is fixed in v59.  I also improved the printing of text formatting shortcuts to stop printing an extra newline when it is used as an argument to a function call.

**Closed** 2023-06-23 12:33 UTC
